shell = "zsh"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.dotfiles-sh]
local = "~/.config/sh"
use = ["{*}.sh"]

[plugins.dotfiles-zsh]
local = "~/.config/zsh"
use = ["{*}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.local-completions]
local = "~/.config/zsh/completions"
apply = ["fpath"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"
