[settings]
idiomatic_version_file_enable_tools = ["python"]

[tools]
gh = "latest"
go = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
node = "lts"
python = "latest"
shellcheck = "latest"
terraform = "latest"
tmux = "latest"
